[tool]
[tool.commitizen]
name = "cz_customize"
version = "0.0.1"
tag_format = "$version"

[tool.commitizen.customize]
message_template = "{{change_type}}{% if issue %}[#{{issue}}]{% issue %} {{message}}"
example = "[!12][ğŸ›] Fix that daamn bug"
# TODO(dauliac) Read doc
schema = "<type> <body>"
schema_pattern = "(feature|bug fix):(\\s.*)"
bump_pattern = "^(break|new|fix|hotfix)"
bump_map = {"break" = "MAJOR", "new" = "MINOR", "fix" = "PATCH", "hotfix" = "PATCH"}
change_type_order = ["BREAKING CHANGE", "feat", "fix", "refactor", "perf"]
info_path = "cz_customize_info.txt"
info = """
This is customized info
"""
# ENDTODO(dauliac) Read doc

[[tool.commitizen.customize.questions]]
type = "list"
name = "change_type"
choices = [
  {value = "ğŸ¨", name = "ğŸ¨ Improve structure / format of the code."},
  {value = "âš¡ï¸", name = "âš¡ï¸ Improve performance."},
  {value = "ğŸ”¥", name = "ğŸ”¥ Improve performance."},
  {value = "ğŸ›", name = "ğŸ› Fix a bug."},
  {value = "ğŸš‘", name = "ğŸš‘ Critical hotfix."},
  {value = "âœ¨", name = "âœ¨ Introduce new features."},
  {value = "ğŸ“", name = "ğŸ“ Introduce new features."},
  {value = "ğŸš€", name = "ğŸš€ Deploy stuff."},
  {value = "ğŸ’„", name = "ğŸ’„ Add or update the UI and style files."},
  {value = "ğŸ‰", name = "ğŸ‰ Initial commit."},
  {value = "âœ…", name = "âœ… Add, update, or pass tests."},
  {value = "ğŸ”’", name = "ğŸ”’ Fix security issues."},
  {value = "ğŸ”–", name = "ğŸ”– Release / Version tags."},
  {value = "ğŸš¨", name = "ğŸš¨ Fix compiler / linter warnings."},
  {value = "ğŸš§", name = "ğŸš§ Work in progress."},
  {value = "ğŸ’š", name = "ğŸ’š Fix CI Build."},
  {value = "â¬‡ï¸", name = "â¬‡ï¸ Downgrade dependencies."},
  {value = "â¬†ï¸", name = "â¬‡ï¸  Ugrade dependencies."},
  {value = "ğŸ“Œ", name = "ğŸ“Œ Pin dependencies to specific version."},
  {value = "ğŸ‘·", name = "ğŸ‘· Add or update CI build system."},
  {value = "ğŸ“ˆ", name = "ğŸ“ˆ Add or update analytics or track code."},
  {value = "â™»ï¸", name = "â™»ï¸ Refactoring code."},
  {value = "â•", name = "â• Add a dependency."},
  {value = "â–", name = "â– Remove a dependency."},
  {value = "ğŸ”§", name = "ğŸ”§ Add or update configuration files."},
  {value = "ğŸ”¨", name = "ğŸ”¨ Add or update development scripts."},
  {value = "ğŸŒ", name = "ğŸŒ Internationalization and localization."},
  {value = "âœï¸", name = "âœï¸ Fix typos ."},
  {value = "ğŸ’©", name = "ğŸ’© Write bad code that needs to be improved."},
  {value = "âª", name = "âª Revert changes."},
  {value = "ğŸ”€", name = "ğŸ”€ Merge branches."},
  {value = "ğŸ“¦", name = "ğŸ“¦ Add or update compiled files or packages."},
  {value = "ğŸ‘½", name = "ğŸ‘½ Update code due to external API changes."},
  {value = "ğŸšš", name = "ğŸšš Move or rename resources (e.g.: files, paths, routes)."},
  {value = "ğŸ“„", name = "ğŸ“„ Add or update license."},
  {value = "ğŸ’¥", name = "ğŸ’¥ Introduce breaking changes."},
  {value = "ğŸ±", name = "ğŸ± Add or update assets."},
  {value = "â™¿ï¸", name = "â™¿ï¸ Improve accessibility."},
  {value = "ğŸ’¡", name = "ğŸ’¡ Add or update comments in source code."},
  {value = "ğŸ»", name = "ğŸ» Write code drunkenly."},
  {value = "ğŸ’¬", name = "ğŸ’¬ Add or update text and literals."},
  {value = "ğŸ—ƒ", name = " ğŸ—ƒPerform database related changes."},
  {value = "ğŸ”Š", name = "ğŸ”Š Add or update logs."},
  {value = "ğŸ”‡", name = "ğŸ”‡ Remove logs."},
  {value = "ğŸ‘¥", name = "ğŸ‘¥ Add or update contributor(s)."},
  {value = "ğŸš¸", name = "ğŸš¸ Improve user experience / usability."},
  {value = "ğŸ—", name = "ğŸ—  Make architectural changes."},
  {value = "ğŸ“±", name = "ğŸ“± Work on responsive design."},
  {value = "ğŸ¤¡", name = "ğŸ¤¡ Mock things."},
  {value = "ğŸ¥š", name = "ğŸ¥š Add or update an easter egg."},
  {value = "ğŸ™ˆ", name = "ğŸ™ˆ Add or update a .gitignore file."},
  {value = "ğŸ“¸", name = "ğŸ“¸ Add or update snapshots."},
  {value = "âš—", name = "âš— Perform experiments."},
  {value = "ğŸ·ï¸", name = "ğŸ·ï¸ Add or update types."},
  {value = "ğŸŒ±", name = "ğŸŒ± Add or update seed files."},
  {value = "ğŸš©", name = "ğŸš© Add, update, or remove feature flags."},
  {value = "ğŸ¥…", name = "ğŸ¥… Catch errors."},
  {value = "ğŸ’«", name = "ğŸ’« Add or update animations and transitions."},
  {value = "ğŸ—‘ï¸", name = "ğŸ—‘ï¸ Deprecate code that needs to be cleaned up."},
  {value = "ğŸ›‚", name = "ğŸ›‚ Work on code related to authorization, roles and permissions."},
  {value = "ğŸ©¹", name = "ğŸ©¹ Simple fix for a non-critical issue."},
  {value = "ğŸ§", name = "ğŸ§ Data exploration/inspection."},
  {value = "âš°ï¸", name = "âš°ï¸ Remove dead code."},
  {value = "ğŸ§ª", name = "ğŸ§ª Add a failing test."},
  {value = "ğŸ‘”", name = "ğŸ‘” Add or update business logic"},
  {value = "ğŸ©º", name = "ğŸ©º Add or update healthcheck."},
  {value = "ğŸ§±", name = "ğŸ§± Infrastructure related changes."},
  {value = "ğŸ§‘â€ğŸ’»", name = "ğŸ§‘â€ğŸ’» Improve developer experience"},
]

# choices = ["feature", "fix"]  # short version
message = "Select the type of change you are committing"

[[tool.commitizen.customize.questions]]
type = "input"
name = "message"
message = "Body."

[[tool.commitizen.customize.questions]]
type = "confirm"
name = "show_message"
message = "Do you want to add body message in commit?"
